import { Categoria, Produto, Configuracoes, Caixa } from '@/types/pos'

export const INITIAL_CATEGORIAS: Categoria[] = [
  {
    id: 'cat-cervejas',
    nome: 'Cervejas',
    cor: '#D97706',
    icone: 'Beer',
    ordem: 1,
    ativo: true,
    descricao: 'Latas, long necks e chopp',
  },
  {
    id: 'cat-drinks',
    nome: 'Drinks & Destilados',
    cor: '#DC2626',
    icone: 'Martini',
    ordem: 2,
    ativo: true,
  },
  {
    id: 'cat-nao-alcoolicos',
    nome: 'Não Alcoólicos',
    cor: '#2563EB',
    icone: 'CupSoda',
    ordem: 3,
    ativo: true,
  },
  {
    id: 'cat-petiscos',
    nome: 'Petiscos',
    cor: '#EA580C',
    icone: 'Utensils',
    ordem: 4,
    ativo: true,
  },
  {
    id: 'cat-combos',
    nome: 'Combos',
    cor: '#059669',
    icone: 'Package',
    ordem: 5,
    ativo: true,
    descricao: 'Pacotes com desmembramento de fichas',
  },
]

export const INITIAL_PRODUTOS: Produto[] = [
  // Cervejas
  {
    id: 'prod-cerveja-lata',
    categoria_id: 'cat-cervejas',
    nome: 'Cerveja Lata 350ml',
    preco: 8.0,
    codigo_rapido: '101',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Long neck / lata gelada',
    controla_estoque: true,
    estoque_atual: 120,
    estoque_minimo: 24,
  },
  {
    id: 'prod-cerveja-long',
    categoria_id: 'cat-cervejas',
    nome: 'Cerveja Long Neck 355ml',
    preco: 10.0,
    codigo_rapido: '102',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Premium gelada',
    controla_estoque: true,
    estoque_atual: 80,
    estoque_minimo: 12,
  },
  {
    id: 'prod-chopp',
    categoria_id: 'cat-cervejas',
    nome: 'Chopp 300ml',
    preco: 12.0,
    codigo_rapido: '103',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Chopp tirado na hora',
  },
  {
    id: 'prod-chopp-500',
    categoria_id: 'cat-cervejas',
    nome: 'Chopp 500ml',
    preco: 18.0,
    codigo_rapido: '104',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Chopp 500ml',
  },

  // Drinks
  {
    id: 'prod-caipirinha',
    categoria_id: 'cat-drinks',
    nome: 'Caipirinha',
    preco: 18.0,
    codigo_rapido: '201',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Limão, vodka ou cachaça',
  },
  {
    id: 'prod-dose-whisky',
    categoria_id: 'cat-drinks',
    nome: 'Dose Whisky',
    preco: 20.0,
    codigo_rapido: '202',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Dose padrão do bar',
  },
  {
    id: 'prod-dose-vodka',
    categoria_id: 'cat-drinks',
    nome: 'Dose Vodka',
    preco: 15.0,
    codigo_rapido: '203',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Dose padrão do bar',
  },
  {
    id: 'prod-drink-especial',
    categoria_id: 'cat-drinks',
    nome: 'Drink Especial da Casa',
    preco: 25.0,
    codigo_rapido: '204',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Receita do Bar Templários',
  },

  // Não alcoólicos
  {
    id: 'prod-agua',
    categoria_id: 'cat-nao-alcoolicos',
    nome: 'Água Mineral 500ml',
    preco: 5.0,
    codigo_rapido: '301',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Com ou sem gás',
    controla_estoque: true,
    estoque_atual: 60,
    estoque_minimo: 12,
  },
  {
    id: 'prod-refri',
    categoria_id: 'cat-nao-alcoolicos',
    nome: 'Refrigerante Lata 350ml',
    preco: 7.0,
    codigo_rapido: '302',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Coca-Cola, Guaraná, Fanta',
    controla_estoque: true,
    estoque_atual: 48,
    estoque_minimo: 12,
  },
  {
    id: 'prod-energetico',
    categoria_id: 'cat-nao-alcoolicos',
    nome: 'Energético 250ml',
    preco: 12.0,
    codigo_rapido: '303',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Lata 250ml',
    controla_estoque: true,
    estoque_atual: 24,
    estoque_minimo: 6,
  },
  {
    id: 'prod-suco',
    categoria_id: 'cat-nao-alcoolicos',
    nome: 'Suco Natural 400ml',
    preco: 10.0,
    codigo_rapido: '304',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Laranja, limão ou maracujá',
  },

  // Petiscos
  {
    id: 'prod-porcao-batata',
    categoria_id: 'cat-petiscos',
    nome: 'Porção Batata Frita',
    preco: 28.0,
    codigo_rapido: '401',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Serve 2 pessoas',
  },
  {
    id: 'prod-porcao-calabresa',
    categoria_id: 'cat-petiscos',
    nome: 'Porção Calabresa Acebolada',
    preco: 32.0,
    codigo_rapido: '402',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Com limão e farofa',
  },
  {
    id: 'prod-porcao-frango',
    categoria_id: 'cat-petiscos',
    nome: 'Porção Frango a Passarinho',
    preco: 35.0,
    codigo_rapido: '403',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Crocante com molho especial',
  },
  {
    id: 'prod-amigao',
    categoria_id: 'cat-petiscos',
    nome: 'Amigão (Misto)',
    preco: 55.0,
    codigo_rapido: '404',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Batata, calabresa e frango',
  },

  // Combos
  {
    id: 'prod-combo-casal',
    categoria_id: 'cat-combos',
    nome: 'Combo Casal (2 Long + 1 Porção)',
    preco: 45.0,
    codigo_rapido: '501',
    emite_ficha_individual: true,
    ativo: true,
    is_combo: true,
    descricao: '2 long necks + batata frita',
    itens_combo: [
      { produto_id: 'prod-cerveja-long', quantidade: 2 },
      { produto_id: 'prod-porcao-batata', quantidade: 1 },
    ],
  },
  {
    id: 'prod-combo-mesa',
    categoria_id: 'cat-combos',
    nome: 'Combo Mesa (4 Latas + Amigão)',
    preco: 80.0,
    codigo_rapido: '502',
    emite_ficha_individual: true,
    ativo: true,
    is_combo: true,
    descricao: '4 cervejas lata + porção mista',
    itens_combo: [
      { produto_id: 'prod-cerveja-lata', quantidade: 4 },
      { produto_id: 'prod-amigao', quantidade: 1 },
    ],
  },
]

export const INITIAL_CONFIG: Configuracoes = {
  nome_evento: 'Show de Prêmios',
  subtitulo_evento: 'Bar Templários',
  cabecalho_cupom: 'BAR TEMPLÁRIOS',
  rodape_cupom: 'Organização: Templários da Paz',
  largura_bobina: '80mm',
  corte_automatico: true,
  impressora_nome: '',
  modo_impressao: 'escpos',
  modo_impressao_padrao: 'individual',
  senha_admin: '1234',
  taxa_servico_habilitada: false,
  auto_imprimir_ao_finalizar: true,
  simular_impressao_tela: false,
  chave_pix_estatica: '',
  nome_beneficiario_pix: 'Templários da Paz',
  cidade_pix: '',
  salt_seguranca: 'TEMPLARIOS-FICHA-2026',
  tema: 'light',
  ficha_mostrar_cabecalho: true,
  ficha_mostrar_logo: false,
  ficha_mostrar_qrcode: false,
  ficha_mostrar_hash: false,
  ficha_mostrar_preco: false,
  ficha_mostrar_data_hora: true,
  ficha_mostrar_operador: false,
  ficha_mostrar_rodape: true,
  ficha_mostrar_imagem_produto: false,
}

export const INITIAL_CAIXA: Caixa = {
  id: 'cx-default-01',
  operador: 'Operador Principal',
  abertura: new Date().toISOString(),
  saldo_inicial: 100.0,
  status: 'fechado',
  observacoes: 'Caixa de exemplo (fechado) — abra um turno real antes de vender',
}
