import { Categoria, Produto, Configuracoes, Caixa } from '@/types/pos'

export const INITIAL_CATEGORIAS: Categoria[] = [
  { id: 'cat-bebidas', nome: 'Bebidas', cor: '#2563EB', icone: 'Beer', ordem: 1 },
  { id: 'cat-comidas', nome: 'Comidas Típicas', cor: '#EA580C', icone: 'Utensils', ordem: 2 },
  { id: 'cat-sobremesas', nome: 'Doces & Sobremesas', cor: '#EC4899', icone: 'Cake', ordem: 3 },
  {
    id: 'cat-brincadeiras',
    nome: 'Brincadeiras & Jogos',
    cor: '#8B5CF6',
    icone: 'Gamepad2',
    ordem: 4,
  },
  { id: 'cat-combos', nome: 'Combos Especiais', cor: '#059669', icone: 'Package', ordem: 5 },
]

export const INITIAL_PRODUTOS: Produto[] = [
  // Bebidas
  {
    id: 'prod-agua',
    categoria_id: 'cat-bebidas',
    nome: 'Água Mineral 500ml',
    preco: 4.0,
    codigo_rapido: '101',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Com ou sem gás',
  },
  {
    id: 'prod-refri',
    categoria_id: 'cat-bebidas',
    nome: 'Refrigerante Lata 350ml',
    preco: 6.0,
    codigo_rapido: '102',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Coca-Cola, Guaraná, Fanta',
  },
  {
    id: 'prod-cerveja-lata',
    categoria_id: 'cat-bebidas',
    nome: 'Cerveja Lata 350ml',
    preco: 8.0,
    codigo_rapido: '103',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Amstel / Heineken',
  },
  {
    id: 'prod-suco-natural',
    categoria_id: 'cat-bebidas',
    nome: 'Suco Natural 400ml',
    preco: 7.0,
    codigo_rapido: '104',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Laranja, Maracujá ou Uva',
  },
  {
    id: 'prod-quentao',
    categoria_id: 'cat-bebidas',
    nome: 'Quentão / Vinho Quente 200ml',
    preco: 8.0,
    codigo_rapido: '105',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Tradicional com especiarias',
  },

  // Comidas
  {
    id: 'prod-pastel-carne',
    categoria_id: 'cat-comidas',
    nome: 'Pastel Frito (Carne)',
    preco: 10.0,
    codigo_rapido: '201',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Pastel crocante de carne moída temperada',
  },
  {
    id: 'prod-pastel-queijo',
    categoria_id: 'cat-comidas',
    nome: 'Pastel Frito (Queijo)',
    preco: 10.0,
    codigo_rapido: '202',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Mussarela derretida',
  },
  {
    id: 'prod-espetinho',
    categoria_id: 'cat-comidas',
    nome: 'Espetinho de Carne / Frango',
    preco: 12.0,
    codigo_rapido: '203',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Acompanha farofa e vinagrete',
  },
  {
    id: 'prod-cachorro-quente',
    categoria_id: 'cat-comidas',
    nome: 'Cachorro Quente Completo',
    preco: 12.0,
    codigo_rapido: '204',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Com 2 salsichas, milho, batata palha',
  },
  {
    id: 'prod-porcao-batata',
    categoria_id: 'cat-comidas',
    nome: 'Porção Batata Frita 400g',
    preco: 15.0,
    codigo_rapido: '205',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Crocante com cheddar e bacon opcional',
  },
  {
    id: 'prod-caldo-verde',
    categoria_id: 'cat-comidas',
    nome: 'Caldo Verde / Feijão 300ml',
    preco: 12.0,
    codigo_rapido: '206',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Com torradas e cheiro verde',
  },

  // Sobremesas
  {
    id: 'prod-churros',
    categoria_id: 'cat-sobremesas',
    nome: 'Churros Recheado',
    preco: 7.0,
    codigo_rapido: '301',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Doce de leite ou chocolate',
  },
  {
    id: 'prod-maca-amor',
    categoria_id: 'cat-sobremesas',
    nome: 'Maçã do Amor',
    preco: 6.0,
    codigo_rapido: '302',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Caramelizada crocante',
  },
  {
    id: 'prod-bolo-pote',
    categoria_id: 'cat-sobremesas',
    nome: 'Bolo no Pote Artesanal',
    preco: 9.0,
    codigo_rapido: '303',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Ninho com Nutella ou Brigadeiro',
  },

  // Brincadeiras
  {
    id: 'prod-pescaria',
    categoria_id: 'cat-brincadeiras',
    nome: 'Pescaria Premiada (1 rodada)',
    preco: 5.0,
    codigo_rapido: '401',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Ganha brinde garantido',
  },
  {
    id: 'prod-boca-palhaco',
    categoria_id: 'cat-brincadeiras',
    nome: 'Boca do Palhaço (3 bolas)',
    preco: 5.0,
    codigo_rapido: '402',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Acerte a boca e ganhe pontos',
  },
  {
    id: 'prod-bingo-cartela',
    categoria_id: 'cat-brincadeiras',
    nome: 'Cartela do Bingo Especial',
    preco: 10.0,
    codigo_rapido: '403',
    emite_ficha_individual: true,
    ativo: true,
    descricao: 'Concorra a grandes prêmios',
  },

  // Combos
  {
    id: 'prod-combo-casal',
    categoria_id: 'cat-combos',
    nome: 'Combo Casal (2 Pastéis + 2 Refri)',
    preco: 28.0,
    codigo_rapido: '501',
    emite_ficha_individual: true,
    ativo: true,
    is_combo: true,
    descricao: 'Economize comprando o combo com 4 fichas desmembradas',
    itens_combo: [
      { produto_id: 'prod-pastel-carne', quantidade: 1 },
      { produto_id: 'prod-pastel-queijo', quantidade: 1 },
      { produto_id: 'prod-refri', quantidade: 2 },
    ],
  },
  {
    id: 'prod-combo-familia',
    categoria_id: 'cat-combos',
    nome: 'Combo Família Festiva (3 Espetos + 3 Refri + 2 Churros)',
    preco: 60.0,
    codigo_rapido: '502',
    emite_ficha_individual: true,
    ativo: true,
    is_combo: true,
    descricao: 'Super combo para a família toda com 8 fichas emitidas',
    itens_combo: [
      { produto_id: 'prod-espetinho', quantidade: 3 },
      { produto_id: 'prod-refri', quantidade: 3 },
      { produto_id: 'prod-churros', quantidade: 2 },
    ],
  },
]

export const INITIAL_CONFIG: Configuracoes = {
  nome_evento: 'Grande Festa da Comunidade 2025',
  subtitulo_evento: 'Quermesse e Festival Gastronômico Beneficente',
  cabecalho_cupom: 'PARÓQUIA SANTO ANTÔNIO - CNPJ 12.345.678/0001-90',
  rodape_cupom: 'Válido apenas para o dia do evento. Não reembolsável.',
  largura_bobina: '80mm',
  corte_automatico: true,
  modo_impressao_padrao: 'individual',
  senha_admin: '1234',
  taxa_servico_habilitada: false,
  auto_imprimir_ao_finalizar: true,
  simular_impressao_tela: true,
  chave_pix_estatica: 'evento@comunidadebeneficente.org.br',
  nome_beneficiario_pix: 'Associação Comunitária Viva Bem',
  cidade_pix: 'São Paulo',
  salt_seguranca: 'FICHA-SECURE-2025-SALT',
  tema: 'light',
  ficha_mostrar_cabecalho: true,
  ficha_mostrar_logo: true,
  ficha_mostrar_qrcode: true,
  ficha_mostrar_hash: true,
  ficha_mostrar_preco: true,
  ficha_mostrar_data_hora: true,
  ficha_mostrar_operador: true,
  ficha_mostrar_rodape: true,
  ficha_mostrar_imagem_produto: true,
}

export const INITIAL_CAIXA: Caixa = {
  id: 'cx-default-01',
  operador: 'Operador Principal',
  abertura: new Date().toISOString(),
  saldo_inicial: 150.0,
  status: 'aberto',
  observacoes: 'Turno padrão inicial com troco de R$ 150,00',
}
